[font]
normal = { family = "ZedMono Nerd Font", style = "Regular" }
bold = { family = "ZedMono Nerd Font", style = "Bold" }
italic = { family = "ZedMono Nerd Font", style = "Italic" }
size = 20.0

[[keyboard.bindings]]
key = "B"
mods = "Command"  # Use "Super" on Linux/Windows
chars = "\u0002"

[general]
import = [
    "~/.config/alacritty/themes/pigment.toml"
]

[env]
TERM = "xterm-256color"

[window]
[window.padding]
x = 5
y = 5
